Chore/jenkins (#23)
* Update README.md

* Feature: webhook 기능 추가 (#21) (#22)

* feature: discord hook 연결

* fix: ci/cd setting

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -1,69 +1,69 @@
-name: 빌드 및 테스트
-
-on:
-  pull_request:
-    branches: [ "main", "dev" ]
-  push:
-    branches: [ "dev" ]
-
-permissions:
-  contents: read
-
-jobs:
-  build:
-    runs-on: ubuntu-latest
-    steps:
-      - name: PR 및 Branch 확인
-        run: |
-          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
-            if [[ "${{ github.event.action }}" == 'opened' || "${{ github.event.action }}" == 'synchronize' ]]; then
-              if [[ "${{ github.event.pull_request.base.ref }}" == 'dev' || "${{ github.event.pull_request.base.ref }}" == 'main' ]]; then
-                echo "Branch is allowed.";
-              else
-                echo "Branch is not allowed.";
-                exit 1;
-              fi
-            else
-              echo "Invalid action for pull request.";
-              exit 1;
-            fi
-          elif [[ "${{ github.event_name }}" == 'push' ]]; then
-            if [[ "${{ github.event.ref }}" == 'refs/heads/dev' || "${{ github.event.ref }}" == 'refs/heads/main' ]]; then
-              echo "Branch is allowed.";
-            else
-              echo "Branch is not allowed.";
-              exit 1;
-            fi
-          else
-            echo "Invalid event.";
-            exit 1;
-          fi
-
-      - name: 체크아웃
-        uses: actions/checkout@v3 # workflow 실행 전, checkout
-
-      - name: JDK 17 설정
-        uses: actions/setup-java@v2
-        with:
-          java-version: 17
-          distribution: 'adopt'
-          java-package: jdk
-          architecture: x64
-          check-latest: false
-          server-id: github
-          overwrite-settings: true
-          job-status: success
-          server-username: GITHUB_ACTOR
-          server-password: GITHUB_TOKEN
-
-      - name: 실행 권한 부여
-        run: chmod +x ./gradlew
-
-      - name: properties 생성
-        run: |
-          mkdir -p ./src/main/resources/
-          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
-          cat ./src/main/resources/application.yml
-
-      - name: 빌드 진행
-        run: ./gradlew build --refresh-dependencies
+#name: 빌드 및 테스트
+#
+#on:
+#  pull_request:
+#    branches: [ "main", "dev" ]
+#  push:
+#    branches: [ "dev" ]
+#
+#permissions:
+#  contents: read
+#
+#jobs:
+#  build:
+#    runs-on: ubuntu-latest
+#    steps:
+#      - name: PR 및 Branch 확인
+#        run: |
+#          if [[ "${{ github.event_name }}" == 'pull_request' ]]; then
+#            if [[ "${{ github.event.action }}" == 'opened' || "${{ github.event.action }}" == 'synchronize' ]]; then
+#              if [[ "${{ github.event.pull_request.base.ref }}" == 'dev' || "${{ github.event.pull_request.base.ref }}" == 'main' ]]; then
+#                echo "Branch is allowed.";
+#              else
+#                echo "Branch is not allowed.";
+#                exit 1;
+#              fi
+#            else
+#              echo "Invalid action for pull request.";
+#              exit 1;
+#            fi
+#          elif [[ "${{ github.event_name }}" == 'push' ]]; then
+#            if [[ "${{ github.event.ref }}" == 'refs/heads/dev' || "${{ github.event.ref }}" == 'refs/heads/main' ]]; then
+#              echo "Branch is allowed.";
+#            else
+#              echo "Branch is not allowed.";
+#              exit 1;
+#            fi
+#          else
+#            echo "Invalid event.";
+#            exit 1;
+#          fi
+#
+#      - name: 체크아웃
+#        uses: actions/checkout@v3 # workflow 실행 전, checkout
+#
+#      - name: JDK 17 설정
+#        uses: actions/setup-java@v2
+#        with:
+#          java-version: 17
+#          distribution: 'adopt'
+#          java-package: jdk
+#          architecture: x64
+#          check-latest: false
+#          server-id: github
+#          overwrite-settings: true
+#          job-status: success
+#          server-username: GITHUB_ACTOR
+#          server-password: GITHUB_TOKEN
+#
+#      - name: 실행 권한 부여
+#        run: chmod +x ./gradlew
+#
+#      - name: properties 생성
+#        run: |
+#          mkdir -p ./src/main/resources/
+#          echo "${{ secrets.APPLICATION }}" > ./src/main/resources/application.yml
+#          cat ./src/main/resources/application.yml
+#
+#      - name: 빌드 진행
+#        run: ./gradlew build --refresh-dependencies
